version: '3'

tasks:
  default:
    cmds:
      - task: test

  run:
    deps:
      - build
    cmds:
      - bin/sandbox
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build sandbox -out=bin/sandbox
    aliases:
      - b
    silent: true
    sources:
      - './sandbox/**/*.odin'
    generates:
      - bin/sandbox

  build_debug:
    cmds:
      - odin build sandbox -out=bin/sandbox-debug -o:none -debug
    aliases:
      - bd
    silent: true
    sources:
      - './sandbox/**/*.odin'
    generates:
      - bin/sandbox-debug

  debug:
    deps:
      - build_debug
    cmds:
      - gdb bin/sandbox-debug
    aliases:
      - d
    silent: true
    method: none

  test:
    cmds:
      - odin test sandbox -out:bin/sandbox
    aliases:
      - t
    method: none
    silent: true
    sources:
      - '**/*.odin'

interval: 250ms
